; arquivo php.ini personalizado
upload_max_filesize = 256M
post_max_size = 516M
memory_limit = 516M
max_execution_time = 300
allow_url_fopen = On

error_log = "/var/log/php_errors.log"
log_errors = On
